In [59]:
import os
import math
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [60]:
data=pd.read_csv('LDADF.csv')

In [61]:
data=data.drop(['Unnamed: 0','class'],axis=1)

In [62]:
target=data['target']
data=data.drop('target',axis=1)
data.head()

pc1       pc2       pc3
0  0.152160 -6.731869  3.355500
1 -0.893968 -4.666330  2.271738
2 -2.980149 -9.230017  1.810825
3 -0.446289 -6.158868  2.690923
4  1.402740 -8.613285  3.925147

In [63]:
xtrain,xtest,ytrain,ytest=train_test_split(data,target,test_size=0.2)

In [64]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Xtrain = scaler.fit_transform(xtrain)
Xtest = scaler.transform(xtest)

In [72]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
#Libraries to Build Ensemble Model : Random Forest Classifier 
# Create the parameter grid based on the results of random search 
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'],'gamma': [1e-3, 1e-4], 'C': [1, 10, 100, 1000]}]
# Performing CV to tune parameters for best SVM fit 
svm_model = GridSearchCV(SVC(), params_grid, cv=5)
svm_model.fit(Xtrain, ytrain)



GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['linear']}])

In [73]:
# View the accuracy score
print('Best score for training data:', svm_model.best_score_,"\n") 

# View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model = svm_model.best_estimator_
Ypred = final_model.predict(Xtest)

Best score for training data: 0.9055971634284887 

Best C: 1 

Best Kernel: linear 

Best Gamma: 0.001 



In [76]:
print(confusion_matrix(ytest,Ypred))
print("\n")
print(classification_report(ytest,Ypred))

print("Training set score for SVM: %f" % final_model.score(Xtrain , ytrain))
print("Testing  set score for SVM: %f" % final_model.score(Xtest  , ytest ))

[[ 25   0   0   1   0   1]
 [  0  43   1   0   0   0]
 [  0   0  34   1   3   8]
 [  1   0   0  42   0  10]
 [  0   0   2   0  61   1]
 [  0   0   6   3   0 173]]


              precision    recall  f1-score   support

           1       0.96      0.93      0.94        27
           2       1.00      0.98      0.99        44
           3       0.79      0.74      0.76        46
           4       0.89      0.79      0.84        53
           5       0.95      0.95      0.95        64
           6       0.90      0.95      0.92       182

    accuracy                           0.91       416
   macro avg       0.92      0.89      0.90       416
weighted avg       0.91      0.91      0.91       416

Training set score for SVM: 0.905592
Testing  set score for SVM: 0.908654
